openapi: "3.0.0"
info:
  title: SuperHeroes Challenge
  version: 1.0.0
servers:
  - url: http://localhost:8082/
    description: This is where my api is
paths:
  /superheroe/{id}:
    get:
      operationId: findSuperheroeById
      summary:  Busca un super heroe dentro del registro.
      tags:
        - superheroe
      parameters:
        - name: id
          in: path
          description: id del superheroe
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuperHeroe' 
    delete:
      operationId: deleteSuperHeroe
      summary: Eliminación de superHeroe.
      tags:
        - superheroe
      parameters:
        - name: id      
          in: path
          description: id del superheroe
          required: true
          schema:
            type: string      
      responses:
        '200':
          description: 'Ok'
                

  /superheroe:                         
    post:
      operationId: createSuperHeroe
      summary: Creación de super heroe.
      tags:
        - superheroe
      requestBody:
        required: true
        description: requets
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SuperHeroe'
      responses:
        '201':
          description: 'Created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuperHeroe'
                
    put:
      operationId: modifySuperHeroe
      summary: Modificación de superHeroe.
      tags:
        - superheroe      
      requestBody:
        required: true
        description: requets
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SuperHeroe'
      responses:
        '200':
          description: 'Ok'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuperHeroe'
                
                                       
  /superheroes:
    get:
      operationId: findAllSuperheroes
      summary:  Busca todos los superheroes del registro.
      tags:
        - superheroe
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuperHeroes'

  /superheroes/{search}:
    get:
      operationId: findAllSuperheroesBySearchCriteria
      summary:  Busca todos los superheroes del registro.
      tags:
        - superheroe
      parameters:
        - name: search
          in: path
          description: Nombre del superheroe
          required: true
          schema:
            type: string        
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuperHeroes'                
                         
components:
  schemas:
    SuperHeroe:
      type: object
      required:
        - name
        - comment  
      properties:
        id:
          type: string
        name:
          type: string
        comment:
          type: string
          
    SuperHeroes:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/SuperHeroe' 
